<a href="https://colab.research.google.com/github/ratel0307/Python/blob/main/Ch20_%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%9C%BC%EB%A1%9C_%EC%9D%B8%EA%B3%B5_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EB%A7%8C%EB%93%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##뼈대 코드

신경망의 세 가지 기능
- 초기화: 입력, 은닉, 출력 노드의 수 설정
- 학습: 학습 데이터들을 통해 학습하고 이에 따라 가중치를 업데이트
- 질의: 입력을 받아 연산한 후 출력 노드에서 답을 전달

In [ ]:
class neuralNetwork:

  #신경망 초기화하기
  def __init__():
    pass

  #신경망 학습시키기
  def train():
    pass

  #신경망에 질의하기
  def query():
    pass

##신경망 초기화하기

In [ ]:
class neuralNetwork:
  def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
    self.inodes = inputnodes
    self.hnodes = hiddennodes
    self.onodes = outputnodes
    self.wih = (np.random.rand(self.hnodes, self.inodes) - 0.5)
    self.who = (np.random.rand(self.onodes, self.hnodes) - 0.5)
    #np.random.rand(A,B)는 AXB 행렬을 0과 1 사이에서 균등 분포를 따르는 난수를 생성
    #가중치 값은 -0.5~+0.5 사이로 설정
    self.lr = learningrate
    pass
  def train():
    pass
  def query():
    pass

In [ ]:
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

learning_rate = 0.3

n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

##신경망의 핵심인 가중치

- (은닉 노드 x 입력 노드)의 크기를 가지는 입력 계층과 은닉 계층 사이의 가중치의 행렬
- (출력 노드 x 은닉 노드)의 크기를 가지는 은닉 계층과 출력 계층 사이의 가중치의 행렬

In [ ]:
import numpy as np

In [ ]:
np.random.rand(3, 3) #0~1 사이의 수 랜덤으로 기입

array([[0.0669673 , 0.96869559, 0.77947874],
       [0.44978621, 0.11829539, 0.57926344],
       [0.16351432, 0.06967876, 0.79426059]])

In [ ]:
np.random.rand(3, 3) - 0.5 #음수 값 가지도록 설정

array([[-0.1338136 , -0.32872948,  0.30845883],
       [-0.1052473 , -0.08723289, -0.08095556],
       [-0.18277092, -0.40850581, -0.42070929]])

In [ ]:
self.wih = (np.random.rand(self.hnodes, self.inodes) - 0.5)
self.who = (np.random.rand(self.onodes, self.hnodes) - 0.5)

NameError: name 'self' is not defined

##신경망에 질의하기

In [ ]:
hidden_inputs = np.dot(self.wih, inputs)

In [ ]:
import scipy.special

In [ ]:
self.activation_function = lambda x: scipy.special.expit(x)

In [ ]:
hidden_outputs = self.activation_function(hidden_inputs)

In [ ]:
final_inputs = np.dot(self.who, hidden_outputs)
final_outputs = self.activation_function(final_inputs)

In [ ]:
##지금까지의 코드

In [ ]:
self.wih = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
self.who = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))

In [ ]:
class neuralNetwork:

  def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):

    self.inodes = inputnodes
    self.hnodes = hiddennodes
    self.onodes = outputnodes

    self.wih = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
    self.who = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))
    #np.random.normal(loc, scale, size)에서 loc은 평균, scale은 표준편차, size는 출력 배열의 크기
    #pow(a,b)는 a를 b만큼 거듭제곱한 값을 계산하는 함수

    self.lr = learningrate

    self.activation_function = lambda x: scipy.special.expit(x)
    #spicy.special.expit은 시그모이드 함수임!
    #메서드로 설정하면 길어지니깐 + 람다함수는 나중에 유연하게 수정도 가능

    pass

  def train():
    pass

  def query(self, inputs_list):
    #입력 리스트를 2차원 행렬로 변환 + 행벡터를 열벡터로!
    inputs = np.array(inputs_list, ndmin=2).T
    hidden_inputs = np.dot(self.wih, inputs)
    hidden_outputs = self.activation_function(hidden_inputs)
    final_inputs = np.dot(self.who, hidden_outputs)
    final_outputs = self.activation_function(final_inputs)

    return final_outputs

In [ ]:
import numpy as np

inputs_list = [1,2,3]
inputs = np.array(inputs_list, ndmin=2)

print(inputs_list)
print(inputs)
print(inputs.T)

[1, 2, 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


##신경망 학습시키기

In [ ]:
#신경망 학습시키기
def train(self, inputs_list, targets_list):
  #입력 리스트를 2차원의 행렬로 변환
  inputs = np.array(inputs_list, ndmin=2).T
  targets = np.array(targets_list, ndmin=2).T

  hidden_inputs = np.dot(self.wih, inputs)
  hidden_outputs = self.activation_function(hidden_inputs)
  final_inputs = np.dot(self.who, hidden_outputs)
  final_outputs = self.activation_function(hidden_outputs)

  output_errors = targets - final_outputs
  hidden_errors = np.dot(self.who.T, output_errors)

  #은닉 계층과 출력 계층 간의 가중치 업데이트
  self.who += self.lr * np.dot((output_errors * final_outputs * (1.0  - final_outputs)), np.transpose(hidden_outputs))
  #입력 계층과 은닉 계층 간의 가중치 업데이트
  self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0  - hidden_outputs)), np.transpose(inputs))

  pass

##완성된 신경망 코드

In [ ]:
class neuralNetwork:

  def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):

    self.inodes = inputnodes
    self.hnodes = hiddennodes
    self.onodes = outputnodes

    self.wih = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
    self.who = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))

    self.lr = learningrate

    self.activation_function = lambda x: scipy.special.expit(x)

    pass

  def train(self, inputs_list, targets_list):
  #입력 리스트를 2차원의 행렬로 변환
    inputs = np.array(inputs_list, ndmin=2).T
    targets = np.array(targets_list, ndmin=2).T

    hidden_inputs = np.dot(self.wih, inputs)
    hidden_outputs = self.activation_function(hidden_inputs)
    final_inputs = np.dot(self.who, hidden_outputs)
    final_outputs = self.activation_function(final_inputs)

    output_errors = targets - final_outputs
    hidden_errors = np.dot(self.who.T, output_errors)

    #은닉 계층과 출력 계층 간의 가중치 업데이트
    self.who += self.lr * np.dot((output_errors * final_outputs * (1.0  - final_outputs)), np.transpose(hidden_outputs))
    #입력 계층과 은닉 계층 간의 가중치 업데이트
    self.wih += self.lr * np.dot((hidden_errors * hidden_outputs * (1.0  - hidden_outputs)), np.transpose(inputs))

    pass

  def query(self, inputs_list):
    #입력 리스트를 2차원 행렬로 변환
    inputs = np.array(inputs_list, ndmin=2).T
    hidden_inputs = np.dot(self.wih, inputs)
    hidden_outputs = self.activation_function(hidden_inputs)
    final_inputs = np.dot(self.who, hidden_outputs)
    final_outputs = self.activation_function(final_inputs)

    return final_outputs